trigger:
  branches:
    include:
    - main

pr: none

jobs:
- job: Job_1
  displayName: ImageEditor Deployment
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self

  - task: NodeTool@0
    displayName: Use Node 14.17.0
    inputs:
      versionSpec: '14.17.0'

  - task: YarnInstaller@3
    displayName: 'Install Yarn'
    inputs:
      versionSpec: '1.22.5'

  - script: npm install -g npm@7
    displayName: 'Installing npm v7'

  - task: Yarn@3
    displayName: 'Yarn Install'
    inputs:
        productionMode: false

  - task: Npm@1
    displayName: ImageEditor Build
    inputs:
      command: 'custom'
      customCommand: 'run build:prod'
